"""empty message

Revision ID: 7186727046bd
Revises: 
Create Date: 2025-11-21 11:25:11.171148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7186727046bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_score', sa.String(length=100), nullable=True))
        batch_op.drop_column('student')
        batch_op.drop_column('teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('max_score')
        batch_op.drop_column('deadline')
        batch_op.drop_column('group')

    # ### end Alembic commands ###
